export default Object.freeze({
  INCOMPLETE_NUMBER: "incomplete_number",
  INVALID_NUMBER: "invalid_number",
  INCOMPLETE_EXPIRY: "incomplete_expiry",
  INVALID_EXPIRY_YEAR: "invalid_expiry_year",
  INVALID_EXPIRY_MONTH: "invalid_expiry_month",
  INCOMPLETE_CVC: "incomplete_cvc",
  INVALID_CVC: "invalid_cvc",
  PAYMENT_INTENT_AUTHENTICATION_FAILURE: "payment_intent_authentication_failure",
  CARD_DECLINED: "card_declined",
  INSUFFICIENT_FUNDS: "insufficient_funds",
  GENERIC_DECLINE: "generic_decline",
  FRAUDULENT: "fraudulent",
  INCORRECT_CVC: "incorrect_cvc",
  LOST_CARD: "lost_card",
  STOLEN_CARD: "stolen_card",
  EXPIRED_CARD: "expired_card",
  PROCESSING_ERROR: "processing_error",
});
